region: us-east-1
facebook_app_id: "not_configured" # see docs/social_logins.md
google_app_id: "217669932408-rpdfmo8j6piq23vistidjmge9051rmdr.apps.googleusercontent.com" # see docs/social_logins.md
#GfYdUF4jLZW6qf2pQy5D9RrM